//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FxxkBlueScreen.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FxxkBlueScreen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,hight=device-hight,minimum-scale=1.0,maximum-scale=1.0,ser-scalable=none&quot;/&gt;
        ///&lt;title&gt;滑稽&lt;/title&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body { 
        ///margin: 0; 
        ///padding: 0; 
        ///position: relative; 
        ///background-position: center; 
        ///width: 100%; 
        ///height: 100%; 
        ///background-size: 100% 100%; 
        ///}
        ///&lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body id=&quot;body&quot; onLoad=&quot;init()&quot;&gt;
        ///
        ///&lt;!--原写法：
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;js/ThreeCanvas.js&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Huaji {
            get {
                return ResourceManager.GetString("Huaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///    &lt;head&gt;
        ///    	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;script src=&quot;http://code.jquery.com/jquery-latest.js&quot; type=&quot;text/javascript&quot;&gt;
        ///        &lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot;&gt;
        ///            window.onload = function() {
        ///                var str1 = &quot;http&quot;
        ///                var myString = location.search.split(&apos;?&apos;)[1].replace(/%20/g, &apos; &apos;);
        ///                var str2 = myString.substring(0, 4); 
        ///                $(&apos;body&apos;).css(&apos;background&apos;, &quot;#&quot; + myS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
    }
}
